# Generated by Django 4.2 on 2024-07-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название точки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_points', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата посещения')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_visits', to='core.employee')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.point')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_employee'),
        ),
    ]
